trigger:
- main  # Adjust this to your branch name or remove if not needed

pool:
  vmImage: 'windows-latest'  # Use the appropriate agent pool
  name: 'Default'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    scriptType: 'ps'
    scriptPath: ''
    scriptContent: |
      # Your PowerShell commands here
      Write-Host "Setting up PowerShell environment..."
      # Example command: Copy-Item or other necessary commands
  displayName: 'Run PowerShell script'

- powershell: |
    $source = "$(Build.Repository.LocalPath)"
    $destination = "\\20.84.103.163\C$\git"
    $username = "pavithrachandrasekar"
    $password = "$(VM_PASSWORD)"
    
    $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
    
    # Test connection to the destination
    Test-Connection -ComputerName 20.84.103.163 -Count 1 -ErrorAction Stop
    
    # Attempt to create PSDrive
    New-PSDrive -Name "RemoteDrive" -PSProvider FileSystem -Root $destination -Credential $credential -Persist
    
    # Copy files
    Copy-Item -Path $source -Destination $destination -Recurse -Credential $credential
  displayName: 'Copy files to VM'
  env:
    VM_PASSWORD: $(VM_PASSWORD)  # Pass VM password from pipeline variables
