trigger:
- main  # Adjust this to your branch name if different

pool:
  name: 'Default'

steps:
- script: |
    echo "Starting file copy..."
    echo "Test message" > $(Build.Repository.LocalPath)\test.txt
  displayName: 'Create test file'

- task: WindowsMachineFileCopy@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    MachineNames: '20.84.103.163'
    AdminUserName: 'pavithrachandrasekar'
    AdminPassword: '$(VM_PASSWORD)'  # Ensure this is correctly set in pipeline secrets
    TargetPath: 'C:\git'
    CleanTargetFolder: true
  displayName: 'Copy files to VM'
