trigger:
- main  # Adjust this to your branch name if different

pool:
  name: 'Default'  # Ensure this matches the name of your agent pool

steps:
- script: echo "Starting file copy to VM"
  displayName: 'Log Start'

- task: WindowsMachineFileCopy@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    MachineNames: '20.84.103.163'  # Replace with your VM's IP address
    AdminUserName: 'pavithrachandrasekar'  # Use the new username
    AdminPassword: '$(VM_PASSWORD)'  # Store VM password in pipeline secrets
    TargetFolder: 'C:\git'
    CleanTargetFolder: false
  displayName: 'Copy files to VM'
